### ISSUE TITLE
[Blazor] Add Blazor Support

### ISSUE THREAD

**Issue by geocine** [kekyo/DupeNukem#18]
How do I suppress these warnings?

![image](https://user-images.githubusercontent.com/507464/233793333-521e98c2-b1e6-4b9b-9326-1908f89915d6.png)

I am running `Blazor` on my `Webview2` . Along with this I am using your https://github.com/kekyo/DupeNukem/issues/1#issuecomment-1415835578 example
```cs
        public Form()
        {
            InitializeComponent();

            var services = new ServiceCollection();
            services.AddWindowsFormsBlazorWebView();
#if DEBUG
            services.AddBlazorWebViewDeveloperTools();
#endif
            blazorWebView1.HostPage = "wwwroot\\index.html";
            blazorWebView1.Services = services.BuildServiceProvider();
            blazorWebView1.BlazorWebViewInitialized += BlazorWebViewInitialized;
            blazorWebView1.RootComponents.Add<Main>("#app");

        }
```

**Comment by geocine** [comment]
Also how do I access `messenger` inside my Blazor pages? It would be convenient if we can inject similar to the Blazor `@inject IJSRuntime JS`  or on the partial class 
```cs
[Inject]
public IJSRuntime JS { get; set; }
```

**Comment by kekyo** [comment]
@geocine This problem is interesting... I have not touched Blazor so I don't know the details, but from the error messages, it seems that DupeNukem messages and Blazor messages are mixed up.

Perhaps it is because they use the same (and only) message sending/receiving channel. This can be very difficult to work around because every WebView implementation I've seen so far (Chromium/Edge/Android) only has a single message send/receive channel.

Do you know of any way to split the message send/receive channel or prevent the impact from happening? If it exists, I would be willing to consider it proactively.

**Comment by geocine** [comment]
I am also trying to figure out , I will need to study Blazor's and DupeNukem's sources. It's either I'll find a way to make them work together or copy the setup API, decorations, services of Blazor and use DupeNukem as dropin replacement.

**Comment by geocine** [comment]
I am also trying to figure out , I will need to study Blazor's and DupeNukem's sources. I'll find a way to make them work together and eventually copy the setup API, decorations, services of Blazor and use DupeNukem as a drop-in replacement. 

In the end I am planning to use ReactJS and not really Razor but I would still want to use the BlazorWebview because it has ways to create custom FileProviders while the raw WebView2 doesn't have. 

For now I'm thinking DupeNukem should have a way to disregard messages. In Blazor's case, disregard messages that starts with `__bwv` for Blazor Web View.

**Comment by kekyo** [comment]
I see, so you are saying that the JavaScript side should be able to identify the message when it is received. Then I can do something about it. NET side is the same. I'll think about it!

**Comment by kekyo** [comment]
@geocine  Improved with latest patch application. I will release 0.24.0 soon, so please try to it.

**Comment by geocine** [comment]
It works, thanks. I can close this
